Traceback (most recent call last):
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.cache/pypoetry/virtualenvs/crypto-hash-functions-lab-06WRUrPI-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
user_name = 'Bob'
password = 'hello_bob'
password_database = load_new_password(user_name, password)
is_valid = verify_password(user_name, password, password_database)
print('Valid password: ', is_valid)

user_name = 'Bob'
password = 'hello_bob_12312'
is_valid = verify_password(user_name, password, password_database)
print('Valid password: ', is_valid)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[9], line 4[0m
[1;32m      2[0m password [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhello_bob[39m[38;5;124m'[39m
[1;32m      3[0m password_database [38;5;241m=[39m load_new_password(user_name, password)
[0;32m----> 4[0m is_valid [38;5;241m=[39m [43mverify_password[49m[43m([49m[43muser_name[49m[43m,[49m[43m [49m[43mpassword[49m[43m,[49m[43m [49m[43mpassword_database[49m[43m)[49m
[1;32m      5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mValid password: [39m[38;5;124m'[39m, is_valid)
[1;32m      7[0m user_name [38;5;241m=[39m [38;5;124m'[39m[38;5;124mBob[39m[38;5;124m'[39m

Cell [0;32mIn[8], line 8[0m, in [0;36mverify_password[0;34m(user_name, password, password_database)[0m
[1;32m      3[0m hash_object [38;5;241m=[39m [38;5;28mstr[39m[38;5;241m.[39mencode(password)
[1;32m      4[0m checker [38;5;241m=[39m {user_name: {[38;5;124m'[39m[38;5;124mSALT[39m[38;5;124m'[39m: salt,
[1;32m      5[0m                        [38;5;124m'[39m[38;5;124mHASH_CODE[39m[38;5;124m'[39m: hashlib[38;5;241m.[39msha256(hash_object)
[1;32m      6[0m                     }
[1;32m      7[0m             }        
[0;32m----> 8[0m [38;5;28;01mreturn[39;00m [43mpassword_database[49m[43m[[49m[43muser_name[49m[43m][49m[43m[[49m[43msalt[49m[43m][49m[38;5;241m.[39mhexdigest() [38;5;241m==[39m checker[38;5;241m.[39mhexdigest()

[0;31mKeyError[0m: 'e7a37046a5854a40babd340784ddc75e'

